SELECT * FROM dbo.KhuyenMai;
SELECT * FROM dbo.KhachHang;
SELECT * FROM dbo.TheLoai;
SELECT * FROM dbo.Sach;
SELECT * FROM dbo.LichSuNhapHang;
SELECT * FROM dbo.ChiTietKhuyenMai;
SELECT * FROM dbo.Account;
SELECT * FROM dbo.HoaDon;
SELECT * FROM dbo.ChiTietHoaDon;